module.exports = {
  0:  { name: "🇫🇷 Франция Прага (grpc)", flag: "FR", speed: "низкий пинг" },
  1:  { name: "🇮🇳 Индия Reality", flag: "IN", speed: "быстрый" },
  2:  { name: "🇨🇭 Швейцария Reality", flag: "CH", speed: "стабильный" },
  3:  { name: "🇩🇪 Германия Hetzner", flag: "DE", speed: "европейский" },
  4:  { name: "🇫🇷 Франция Прага #2", flag: "FR", speed: "резерв" },
  5:  { name: "🇬🇧 Великобритания Reality", flag: "GB", speed: "низкий пинг" },
  6:  { name: "🇺🇸 США Вирджиния Reality", flag: "US", speed: "Netflix" },
  7:  { name: "🇪🇸 Испания Reality", flag: "ES", speed: "юг Европы" },
  8:  { name: "🇩🇪 Германия Sandking", flag: "DE", speed: "Reality" },
  9:  { name: "🇫🇷 Франция Прага #3", flag: "FR", speed: "резерв" },
  10: { name: "🇧🇪 Бельгия Reality", flag: "BE", speed: "низкий пинг" },
  11: { name: "🇩🇪 Германия Darkterror", flag: "DE", speed: "Reality" },
  12: { name: "🇫🇮 Финляндия Reality", flag: "FI", speed: "север" },
  13: { name: "🇹🇷 Турция Reality", flag: "TR", speed: "Ближний Восток" },
  14: { name: "🇺🇸 США Reality #2", flag: "US", speed: "альтернатива" },
  15: { name: "🇫🇮 Финляндия Хельсинки", flag: "FI", speed: "Reality" },
  16: { name: "🇲🇾 Малайзия TLS", flag: "MY", speed: "ЮВА" },
  17: { name: "🇩🇪 Германия Bonefletcher", flag: "DE", speed: "Reality" },
  18: { name: "🇩🇪 Германия Graygoat", flag: "DE", speed: "Reality" },
  19: { name: "🇮🇳 Индия VMess #1", flag: "IN", speed: "VMess" },
  20: { name: "🇮🇳 Индия VMess #2", flag: "IN", speed: "VMess" },
  21: { name: "🇦🇺 Австралия VMess #1", flag: "AU", speed: "VMess" },
  22: { name: "🇦🇺 Австралия VMess #2", flag: "AU", speed: "VMess" },
  23: { name: "🇩🇪 Германия Tuskar", flag: "DE", speed: "Reality" },
  24: { name: "🇩🇪 Германия ZeusOlympus", flag: "DE", speed: "Reality" },
  25: { name: "🇩🇪 Германия Antimage", flag: "DE", speed: "Reality" },
  26: { name: "🇭🇰 Гонконг Trojan", flag: "HK", speed: "Азия" },
  27: { name: "🇩🇪 Германия Trojan Burger", flag: "DE", speed: "Trojan" },
  28: { name: "🇩🇪 Германия VK-Portal", flag: "DE", speed: "Reality" },
  29: { name: "🇩🇪 Германия Yandex", flag: "DE", speed: "Reality" },
  30: { name: "🇳🇱 Нидерланды WS", flag: "NL", speed: "низкий пинг" },
  31: { name: "🇺🇸 США IPforVetra", flag: "US", speed: "grpc" },
  32: { name: "🇺🇸 США TellMeTheTrue", flag: "US", speed: "TLS+grpc" },
  33: { name: "🇫🇷 Франция Прага #4", flag: "FR", speed: "резерв" },
  34: { name: "🇳🇱 Нидерланды Shadowsocks", flag: "NL", speed: "SS" },
  35: { name: "🇯🇵 Япония VMess", flag: "JP", speed: "VMess" },
  36: { name: "🇮🇳 Индия VMess #3", flag: "IN", speed: "VMess" },
  37: { name: "🇹🇭 Таиланд VMess", flag: "TH", speed: "VMess" },
  38: { name: "🇮🇩 Индонезия VMess #1", flag: "ID", speed: "VMess" },
  39: { name: "🇮🇩 Индонезия VMess #2", flag: "ID", speed: "VMess" },
  40: { name: "🇮🇩 Индонезия VMess #3", flag: "ID", speed: "VMess" }
};


